[package]
name = "day_03"
version = "1.0.0"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "129fccae003d" }
[addresses]
challenge = "0x0"

